#!/usr/bin/env node
// refresh_market_data.mjs — regenerate market/data.js for the Weather × Markets page.
//
// Fetches three free, no-key FRED CSV series and writes the last 90 observations
// of each (enough for 1-day / 30-day deltas and a 90-day sparkline), plus full
// provenance (source URLs + fetchedAt). FRED daily series publish end-of-day,
// so the latest observation typically trails today by 1-3 business days.
//
// Usage:
//   node refresh_market_data.mjs [--out <path>]
//
// Default output: <script dir>/../pub/market/data.js (the live working copy the
// daily automation pushes from). Override with --out or MARKET_OUT env var.

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url));

const SERIES = [
  { key: "wti",   id: "DCOILWTICO",   label: "WTI Crude Oil (Cushing, OK)",        short: "WTI",        unit: "$/bbl",   dec: 2 },
  { key: "brent", id: "DCOILBRENTEU", label: "Brent Crude Oil (Europe)",           short: "Brent",      unit: "$/bbl",   dec: 2 },
  { key: "hh",    id: "DHHNGSP",      label: "Henry Hub Natural Gas Spot Price",   short: "Henry Hub",  unit: "$/MMBtu", dec: 2 },
];

const WINDOW = 90; // observations kept per series

const csvUrl = (id) => `https://fred.stlouisfed.org/graph/fredgraph.csv?id=${id}`;

async function fetchSeries(s) {
  const res = await fetch(csvUrl(s.id), {
    headers: { "user-agent": "og-weather-briefs market refresh (contact: lyra@taborlin.co)" },
  });
  if (!res.ok) throw new Error(`${s.id}: HTTP ${res.status}`);
  const text = await res.text();
  const points = [];
  for (const line of text.trim().split(/\r?\n/).slice(1)) {
    // FRED CSV rows: DATE,VALUE — missing observations are "."
    const m = line.match(/^(\d{4}-\d{2}-\d{2}),(.+)$/);
    if (!m) continue;
    const v = Number(m[2]);
    if (!Number.isFinite(v)) continue;
    points.push([m[1], v]);
  }
  if (points.length < 31) throw new Error(`${s.id}: only ${points.length} valid observations — refusing to write a thin dataset`);
  return points;
}

function parseArgs(argv) {
  const out = { out: null };
  for (let i = 0; i < argv.length; i++) {
    if (argv[i] === "--out" && argv[i + 1]) out.out = argv[++i];
  }
  return out;
}

async function main() {
  const args = parseArgs(process.argv.slice(2));
  const outPath = resolve(args.out || process.env.MARKET_OUT || join(SCRIPT_DIR, "..", "pub", "market", "data.js"));

  const fetchedAt = new Date().toISOString();
  const series = {};
  const provenance = [];

  for (const s of SERIES) {
    const points = await fetchSeries(s);
    const kept = points.slice(-WINDOW);
    series[s.key] = {
      id: s.id, label: s.label, short: s.short, unit: s.unit, decimals: s.dec,
      observations: kept.length,
      window: { from: kept[0][0], to: kept[kept.length - 1][0] },
      points: kept,
    };
    provenance.push({
      id: s.id, label: s.label,
      url: csvUrl(s.id),
      landing: `https://fred.stlouisfed.org/series/${s.id}`,
      observationsKept: kept.length, totalObservationsFetched: points.length,
    });
    console.error(`ok ${s.id}: ${kept.length} obs ${kept[0][0]} → ${kept[kept.length - 1][0]} (latest ${kept[kept.length - 1][1].toFixed(s.dec)})`);
  }

  const data = {
    title: "Weather × Markets — price data",
    fetchedAt,
    updatedNote: "FRED daily series publish end-of-day; the latest observation typically trails today by 1-3 business days.",
    sourceCredit: "Source: FRED (St. Louis Fed), series EIA",
    series,
    provenance,
  };

  // Preserve the daily NOTE block (delimited by --- NOTE / --- END NOTE markers) if the
  // previous data.js carried one — the 15:00 UTC automation owns that block; a FRED
  // refresh must never wipe it (a lost NOTE silently blanks the note section).
  let noteBlock = "";
  try {
    const old = readFileSync(outPath, "utf8");
    const m = old.match(/\/\/ --- NOTE[\s\S]*?\/\/ --- END NOTE ---\r?\n?/);
    if (m) noteBlock = "\n" + m[0];
  } catch {}

  const body = `// AUTO-GENERATED by og-intel/tools/refresh_market_data.mjs — do not edit by hand.\n` +
    `// Fetched ${fetchedAt} from fred.stlouisfed.org (free CSV endpoints, no API key).\n` +
    `const MARKET_DATA = ${JSON.stringify(data, null, 1)};\n` + noteBlock;

  mkdirSync(dirname(outPath), { recursive: true });
  writeFileSync(outPath, body, "utf8");

  // Hygiene guard: a single dropped quote blanks the whole page silently.
  const check = await import("node:child_process").then(cp => cp.spawnSync("node", ["--check", outPath], { encoding: "utf8" }));
  if (check.status !== 0) {
    console.error(`SYNTAX CHECK FAILED — not trusting ${outPath}:\n${check.stderr}`);
    process.exit(1);
  }
  console.error(`wrote ${outPath} (node --check passed)`);
}

main().catch((e) => { console.error(`refresh_market_data: ${e.message}`); process.exit(1); });
